# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DDTM_GenerationRapport
                                 A QGIS plugin
 Génère un rapport PDF
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-10
        copyright            : (C) 2025 by Louis Huguet
        email                : lshgt@hotmail.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DDTM_GenerationRapport class from file DDTM_GenerationRapport.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .DDTM_GenerationRapport import DDTM_GenerationRapport
    return DDTM_GenerationRapport(iface)
